name: SpreenStudios
version: '${project.version}'
main: datta.core.Core
api-version: '1.19'
authors: [datta]
softdepend:
  - voicechat
permissions:
  spreenstudios.voicechat:
    description: Allows to broadcast your voice
commands:
 info:
   permission: 'spreenstudios.info'